version: "3.9"

services:
  beam_db:
    container_name: beam_db
    image: mysql:5.7
    volumes:
      - db_data_beam:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: beam
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  beam_wp:
    container_name: beam_wp
    depends_on:
      - beam_db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8003:80"
    restart: always
    environment:
      VIRTUAL_HOST: mo.tmy.io
      WORDPRESS_DB_HOST: beam_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: beam
volumes:
  db_data_beam: {}